### ISSUE TITLE
Stop stealing idea and claims it is your...

### ISSUE THREAD

**Issue by iNoSec2** [Processus-Thief/RemClip#1]
At least give the author of the original idea and code which was taken for your tools...
You're a fraud...

**Comment by ProcessusT** [comment]
Done 😉 Original idea didn't include web server to export data
Link was added to main readme
Have a nice day too 👍![image](https://user-images.githubusercontent.com/13833925/208241531-a6543d92-133b-4c95-8c44-4c77528f9055.jpeg)
